# Generated by Django 4.2.7 on 2024-09-20 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cold_drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.colddrink')),
                ('tiffin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tiffin')),
            ],
        ),
    ]
