# Generated by Django 4.2.7 on 2024-09-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colddrink',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='price',
            field=models.IntegerField(),
        ),
    ]
