# Generated by Django 4.2.7 on 2024-09-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_colddrink_price_alter_tiffin_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cold_drink',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tiffin',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
